# Generated by Django 3.1.1 on 2020-09-08 02:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=users.models.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('admin', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
